import { monthKeyFor, totalForMonth, buildSummary, reportFileName } from './app-core.js';

const $ = (selector) => document.querySelector(selector);
const dbName = 'benzin95-ledger-db';
let selectedFile = null;
let selectedPreviewUrl = null;
let toastTimer;

function openDatabase() { return new Promise((resolve, reject) => { const request = indexedDB.open(dbName, 1); request.onupgradeneeded = () => request.result.createObjectStore('checks', { keyPath: 'id' }); request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error); }); }
async function withStore(mode, operation) { const db = await openDatabase(); return new Promise((resolve, reject) => { const transaction = db.transaction('checks', mode); const request = operation(transaction.objectStore('checks')); request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error); transaction.oncomplete = () => db.close(); transaction.onerror = () => reject(transaction.error); }); }
const allChecks = () => withStore('readonly', (store) => store.getAll());
const saveCheck = (check) => withStore('readwrite', (store) => store.put(check));
const removeCheck = (id) => withStore('readwrite', (store) => store.delete(id));
const money = (value) => new Intl.NumberFormat('en-IL', { style: 'currency', currency: 'ILS' }).format(Number(value) || 0);
const displayMonth = (key) => new Intl.DateTimeFormat('en', { month: 'long', year: 'numeric' }).format(new Date(`${key}-01T12:00:00`));
const dateText = (date) => new Intl.DateTimeFormat('en', { day: 'numeric', month: 'short', year: 'numeric' }).format(new Date(`${date}T12:00:00`));
const escapeHTML = (value = '') => String(value).replace(/[&<>'"]/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#039;', '"': '&quot;' })[char]);
function showToast(message) { const toast = $('#toast'); toast.textContent = message; toast.classList.add('show'); clearTimeout(toastTimer); toastTimer = setTimeout(() => toast.classList.remove('show'), 2800); }

function setSelectedFile(file) { if (!file) return; if (!file.type.startsWith('image/')) { showToast('Select an image file.'); return; } selectedFile = file; if (selectedPreviewUrl) URL.revokeObjectURL(selectedPreviewUrl); selectedPreviewUrl = URL.createObjectURL(file); $('#imagePreview').src = selectedPreviewUrl; $('#checkForm').hidden = false; $('#emptyCaptureHint').hidden = true; $('#checkDate').value = new Date().toISOString().slice(0, 10); updateMonthHint(); }
function clearSelectedFile() { selectedFile = null; if (selectedPreviewUrl) URL.revokeObjectURL(selectedPreviewUrl); selectedPreviewUrl = null; $('#checkForm').reset(); $('#checkForm').hidden = true; $('#emptyCaptureHint').hidden = false; $('#cameraInput').value = ''; $('#galleryInput').value = ''; }
function updateMonthHint() { const key = monthKeyFor($('#checkDate').value); $('#monthHint').textContent = key ? `Saved under ${displayMonth(key)}` : ''; }

async function refresh() { const checks = (await allChecks()).sort((a, b) => b.date.localeCompare(a.date)); const summary = buildSummary(checks); $('#grandTotal').textContent = money(summary.total); $('#checkCount').textContent = summary.count; renderMonths(checks, summary.months); renderCalendar(checks, summary.months); }
function renderMonths(checks, months) { const list = $('#monthList'); if (!months.length) { list.innerHTML = '<div class="empty-state">No checks yet. <a href="#capture">Add one</a>.</div>'; return; } list.innerHTML = months.map((month) => { const monthChecks = checks.filter((check) => check.month === month.month); const finalized = monthChecks.some((check) => check.calculatedAt); return `<article class="month-card"><div class="month-top"><div class="month-label">${displayMonth(month.month)}</div><div class="month-meta">${month.count} ${month.count === 1 ? 'check' : 'checks'}${finalized ? ' · calculated' : ''}</div><div class="month-total">${money(month.amount)}</div><button class="calculate-button" data-calculate="${month.month}">${finalized ? 'Recalculate' : 'Calculate'}</button></div><div class="check-rows">${monthChecks.map((check) => `<div class="check-row"><img class="thumb" src="${URL.createObjectURL(check.image)}" alt="Check from ${check.date}"><div class="check-info"><b>${escapeHTML(check.note || 'Fuel check')}</b><span>${dateText(check.date)}</span></div><div class="check-amount">${money(check.amount)}</div><button class="delete-button" data-delete="${check.id}">Remove</button></div>`).join('')}</div></article>`; }).join(''); }
function renderCalendar(checks, months) { const year = new Date().getFullYear(); const calculated = new Map(); for (const month of months) { const monthChecks = checks.filter((check) => check.month === month.month); if (monthChecks.some((check) => check.calculatedAt)) calculated.set(month.month, totalForMonth(checks, month.month)); } $('#calendarGrid').innerHTML = Array.from({ length: 12 }, (_, index) => { const key = `${year}-${String(index + 1).padStart(2, '0')}`; const amount = calculated.get(key); return `<div class="calendar-month ${amount !== undefined ? 'has-spend' : ''}"><b>${new Intl.DateTimeFormat('en', { month: 'short' }).format(new Date(year, index, 1)).toUpperCase()}</b>${amount !== undefined ? `<div class="spent">${money(amount)}</div><small>calculated</small>` : '<div class="spent">—</div>'}</div>`; }).join(''); }
function navigate() { const page = location.hash.slice(1) || 'capture'; document.querySelectorAll('[data-page]').forEach((section) => section.hidden = section.dataset.page !== page); document.querySelectorAll('[data-route]').forEach((link) => link.classList.toggle('active', link.dataset.route === page)); }

function imageToJpeg(blob) { return new Promise((resolve, reject) => { const image = new Image(); const url = URL.createObjectURL(blob); image.onload = () => { const max = 1800; const scale = Math.min(1, max / Math.max(image.width, image.height)); const canvas = document.createElement('canvas'); canvas.width = Math.max(1, Math.round(image.width * scale)); canvas.height = Math.max(1, Math.round(image.height * scale)); const context = canvas.getContext('2d'); context.fillStyle = '#ffffff'; context.fillRect(0, 0, canvas.width, canvas.height); context.drawImage(image, 0, 0, canvas.width, canvas.height); URL.revokeObjectURL(url); resolve({ data: canvas.toDataURL('image/jpeg', .9), width: canvas.width, height: canvas.height }); }; image.onerror = () => { URL.revokeObjectURL(url); reject(new Error('This image could not be added to the PDF.')); }; image.src = url; }); }
async function exportPdf() { if (!window.jspdf?.jsPDF) { showToast('PDF generator is still loading. Try again.'); return; } const month = monthKeyFor(new Date().toISOString().slice(0, 10)); const checks = (await allChecks()).filter((check) => check.month === month).sort((a, b) => a.date.localeCompare(b.date)); const doc = new window.jspdf.jsPDF({ unit: 'mm', format: 'a4', compress: true }); const pageWidth = doc.internal.pageSize.getWidth(); const pageHeight = doc.internal.pageSize.getHeight(); const margin = 18; const total = totalForMonth(checks, month); doc.setProperties({ title: `Benzin95 Ledger — ${displayMonth(month)}` }); doc.setFillColor(23, 33, 43); doc.rect(0, 0, pageWidth, 36, 'F'); doc.setTextColor(255, 255, 255); doc.setFont('helvetica', 'bold'); doc.setFontSize(19); doc.text('BENZIN95 LEDGER', margin, 18); doc.setFont('helvetica', 'normal'); doc.setFontSize(11); doc.text(displayMonth(month), margin, 27); doc.setTextColor(23, 33, 43); doc.setFont('helvetica', 'bold'); doc.setFontSize(31); doc.text(money(total), margin, 67); doc.setFont('helvetica', 'normal'); doc.setFontSize(11); doc.setTextColor(101, 115, 131); doc.text(`Fuel total · ${checks.length} ${checks.length === 1 ? 'check' : 'checks'}`, margin, 76); doc.setDrawColor(217, 224, 232); doc.line(margin, 88, pageWidth - margin, 88); doc.setTextColor(23, 33, 43); doc.setFontSize(10); doc.text(`Generated ${new Intl.DateTimeFormat('en', { day: 'numeric', month: 'short', year: 'numeric' }).format(new Date())}`, margin, 101); doc.setTextColor(101, 115, 131); doc.setFontSize(9); doc.text('Pages that follow contain the original check images.', margin, 110); checks.forEach(async () => {}); for (const [index, check] of checks.entries()) { doc.addPage(); const image = await imageToJpeg(check.image); const maxWidth = pageWidth - margin * 2; const maxHeight = pageHeight - 58; const scale = Math.min(maxWidth / image.width, maxHeight / image.height); const width = image.width * scale; const height = image.height * scale; doc.setTextColor(23, 33, 43); doc.setFont('helvetica', 'bold'); doc.setFontSize(13); doc.text(`Check ${index + 1} · ${dateText(check.date)}`, margin, 15); doc.setFont('helvetica', 'normal'); doc.setFontSize(11); doc.text(money(check.amount), pageWidth - margin, 15, { align: 'right' }); if (check.note) { doc.setTextColor(101, 115, 131); doc.setFontSize(9); doc.text(check.note, margin, 22); } doc.addImage(image.data, 'JPEG', (pageWidth - width) / 2, 30, width, height, undefined, 'FAST'); doc.setTextColor(101, 115, 131); doc.setFontSize(8); doc.text(`${index + 2} / ${checks.length + 1}`, pageWidth - margin, pageHeight - 10, { align: 'right' }); } doc.save(reportFileName(month)); showToast('PDF report downloaded.'); }

$('#cameraInput').addEventListener('change', (event) => setSelectedFile(event.target.files[0])); $('#galleryInput').addEventListener('change', (event) => setSelectedFile(event.target.files[0])); $('#clearImage').addEventListener('click', clearSelectedFile); $('#checkDate').addEventListener('change', updateMonthHint);
$('#checkForm').addEventListener('submit', async (event) => { event.preventDefault(); if (!selectedFile) return; const date = $('#checkDate').value; const amount = Number($('#checkAmount').value); if (!date || !Number.isFinite(amount) || amount < 0) { showToast('Enter a valid date and total.'); return; } await saveCheck({ id: crypto.randomUUID(), date, month: monthKeyFor(date), amount, note: $('#checkNote').value.trim(), image: selectedFile, createdAt: new Date().toISOString(), calculatedAt: null }); clearSelectedFile(); await refresh(); location.hash = 'records'; showToast('Check saved.'); });
$('#monthList').addEventListener('click', async (event) => { const deleteId = event.target.dataset.delete; const month = event.target.dataset.calculate; if (deleteId && confirm('Remove this check?')) { await removeCheck(deleteId); await refresh(); showToast('Check removed.'); } if (month) { const checks = await allChecks(); const timestamp = new Date().toISOString(); await Promise.all(checks.filter((check) => check.month === month).map((check) => saveCheck({ ...check, calculatedAt: timestamp }))); await refresh(); showToast(`${displayMonth(month)}: ${money(totalForMonth(checks, month))}`); } });
for (const button of [$('#exportButton'), $('#exportButtonSecondary')]) button.addEventListener('click', exportPdf); window.addEventListener('hashchange', navigate); window.addEventListener('beforeunload', () => { if (selectedPreviewUrl) URL.revokeObjectURL(selectedPreviewUrl); }); navigate(); refresh();
